### ISSUE TITLE
Second wall stretch cannot be build

### ISSUE THREAD

**Issue by sanderd17** [na-Itms/0ad#10]
Steps to reproduce:

* Build a wall with two towers and one wall length
* wait until it is constructed
* Try to build a second wall, with the towers snapped to each other

The obstruction groups are still set correctly for the first wall, so that's not the problem. But it works with wall foundations, and I think only the ID of the foundation vs the fully-build wall differs.

**Comment by sanderd17** [comment]
The issue is trivial to solve.

It's caused because wall segments use the default passability class (in order to be reachable by units so they can build and attack it, but also be able to block all paths). As the current default passability class also includes building footprints, building a new wall part sees the existing part as obstructed, so it can't append to it.

By changing the class from "default" to "default-territory-only" on BuildRestrictions.js line 122, the building obstructions are ignored first (they are treated correctly later on in the code) and the issue is fixed.(the comment should also be modified though).

**Comment by na-Itms** [comment]
Ah, this is similar to the broken AI issue, Philip hadn't originally considered useful to have some pass class for terrain only
