### ISSUE TITLE
Static rasterization for the AI takes too long

### ISSUE THREAD

**Issue by sanderd17** [na-Itms/0ad#12]
Every time a building gets completed, the AI gets a new obstruction map.

But CCmpObstructionManager::Rasterize can easily take a few 100 ms for an average map now. Which results in a huge lag spike when the grid is calculated, followed by a speedy catchup in the turns where there's no lag.

The speed of the method seems to depend a lot on the number of buildings on the map, and it's especially the static part that's very slow. If you play against multiple AI, every few turns there's a new building completed, every time with a lag spike.

**Comment by sanderd17** [comment]
This should make rasterization a lot faster: http://pastebin.com/h05xUtdy (after applying it, it still shows up in the profiler, but next to other peaks).

Don't forget to apply http://trac.wildfiregames.com/changeset/16695 to test the AI (else the AI can't read the territory and won't build anything).

**Comment by na-Itms** [comment]
Thanks for that patch. It fixes the TODO on line 81 of the patch, if I understand correctly?

Actually there is a far more important optimization I can do (or at least I think so). I will work on it tonight, but I'll include this one on top, thanks a lot.

**Comment by na-Itms** [comment]
After working a bit on the other optimization (which would be updating only the parts of the passability map that need to be updated) it appears that it would add a lot of changes if I want to do this cleverly, so if your patch improves performance enough to remove these 300ms spikes, I'll commit the other optimization only after merging.

**Comment by sanderd17** [comment]
I also expected that updating parts of the passability map would be an improvement. However, this rasterize code was very inefficient too. Even at the start of the game, the lag was clearly visible. While only buildings and mines are taken into account for the static passability (and no trees).

**Comment by na-Itms** [comment]
Ok :) I'm waiting for you to fix the sim state issue then :)

**Comment by sanderd17** [comment]
So, the patch won't keep the same simulation state, as the old code had a 1-tile too tight bounding box, which isn't bad with such small tiles, but it's more correct when fixed.

Here's the new patch, with cleaner code and more ENSUREs: http://pastebin.com/QbxLw6Rg

**Comment by na-Itms** [comment]
The game crashes when trying to load the scenario map Arcadia, with an ENSURE failing in RasterizeRectWithClearance.

**Comment by sanderd17** [comment]
As discussed on IRC, the problem is that the obstruction of fences is too small, which makes that the obstruction square doesn't cover a continious region of obstructed tiles, and the code expects a continious region (at least diagonally continious).

As the map maker probably also wants a continious region (and no gaps for fences f.e.), it's best to require a minimum obstruction size.

This patch adds a minimum to the obstruction size, and modifies the three affected templates: http://pastebin.com/KL3RRYa5

**Comment by na-Itms** [comment]
So you get confused by comparison operators? :D
