### ISSUE TITLE
AI not working with the new pathfinder

### ISSUE THREAD

**Issue by kanetaka2014** [na-Itms/0ad#2]
When I play as single player, I noticed the AI never builds anything so just gathers resources. I don't know when this issue happened but seems before our renewal.

**Comment by na-Itms** [comment]
The current AI API is not working with the current pathfinder. The branch AI-pathfinding is the place where I am going to make experiments, at the moment nothing is definitive.

The objective is to move the AI internal pathfinder to the engine side and make it share code with the long-range unit pathfinder.

**Comment by na-Itms** [comment]
The original issue has been fixed, now waiting for mimo to use the new API with Petra, but this might happen after SVN merging.
