### ISSUE TITLE
Short pathfinder errors

### ISSUE THREAD

**Issue by na-Itms** [na-Itms/0ad#4]
Sometimes, unit shortpathing to avoid collisions end up at unwanted positions. 
I have not investigated yet but I open this ticket to file the issue somewhere.

**Comment by kanetaka2014** [comment]
The following commit inserts a dummy obstruction square and then sometimes forces the unit to detour.
https://github.com/na-Itms/0ad/commit/e4603aa4f45fc10f75482a1c4bbfbc7aabc90714

![screenshot0028](https://cloud.githubusercontent.com/assets/9270128/7006286/e51dfcbe-dcba-11e4-8dca-278f63a879f5.gif)

**Comment by na-Itms** [comment]
Most of the unit motion has been fixed in recent commits. In particular, units stopping their motion at unwanted positions seem to have been fixed.
