### ISSUE TITLE
New formations from split groups don't listen

### ISSUE THREAD

**Issue by sanderd17** [na-Itms/0ad#8]
Steps to reproduce:

* Take at least 4 units
* Task them somewhere so they form a formation
* When they're finished walking, task about half the units somewhere else (so you have two formations)
* When that half is finished walking, select all units again (that were in the first formation) and task them somewhere. They won't move on the first command, nor on subsequent commands to the same position (which requires you to not move your mouse), but they will move to a subsequent command if it's not to the same position.

**Comment by na-Itms** [comment]
Removed formations in the branch. If more issues don't arise, this ticket can be closed.
